# Generated by Django 4.2.9 on 2024-04-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_city_url_title_province_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.province'),
        ),
    ]
