# Generated by Django 4.2.9 on 2024-05-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_publicplace_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('IR', 'ایرانی'), ('F', 'اتباع')], default='IR', max_length=300),
        ),
    ]
