# Generated by Django 4.2.9 on 2024-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_birth_date_profile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'بانو'), ('M', 'آقا')], default='F', max_length=10),
        ),
    ]
