# Generated by Django 4.2.9 on 2024-05-05 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_publicplace_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='director',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
