# Generated by Django 4.2.9 on 2024-05-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_publicplace_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='district',
            field=models.CharField(default='zand', max_length=100),
            preserve_default=False,
        ),
    ]
