# Generated by Django 4.2.9 on 2024-05-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_publicplace_city_alter_publicplace_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicplace',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.province'),
            preserve_default=False,
        ),
    ]
