# Generated by Django 4.2.9 on 2024-05-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='marital_status',
        ),
    ]
