# Generated by Django 4.2.9 on 2024-05-13 04:56

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_volunteer_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='account.city'),
        ),
    ]
