# Generated by Django 4.2.9 on 2024-05-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_publicplace_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='slug',
        ),
    ]
