# Generated by Django 4.2.9 on 2024-01-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
