# Generated by Django 4.2.9 on 2024-01-12 13:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_province_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_level', models.CharField(max_length=20, unique=True, verbose_name='دوره آموزشی')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=20, unique=True, verbose_name='پایه تحصیلی')),
                ('edu_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('educational_district', models.IntegerField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city')),
                ('director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.province')),
                ('school_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='Code Melli')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('last_password_reset_on', models.DateTimeField(auto_now_add=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('special_condition', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('slug', models.SlugField(default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.city')),
                ('edu_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel')),
                ('free_time', models.ManyToManyField(to='application.availabletime')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.grade')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.major')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.province')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkilledVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='Code Melli')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('last_password_reset_on', models.DateTimeField(auto_now_add=True)),
                ('education', models.CharField(blank=True, choices=[('UG', 'Under Graduate'), ('B', 'BACHELOR'), ('M', 'MASTER'), ('PHD', 'PHD')], max_length=10, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('slug', models.SlugField(default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.city')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.job')),
                ('offered_skill', models.ManyToManyField(to='application.skill')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.skilltype'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.skilltype'),
        ),
        migrations.CreateModel(
            name='EducationalVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='Code Melli')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('last_password_reset_on', models.DateTimeField(auto_now_add=True)),
                ('education', models.CharField(blank=True, choices=[('UG', 'Under Graduate'), ('B', 'BACHELOR'), ('M', 'MASTER'), ('PHD', 'PHD')], max_length=10, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.city')),
                ('edu_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel', verbose_name='Pereffered Level')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.grade', verbose_name='Pereffered Grade')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.job')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.major', verbose_name='Pereffered Major')),
                ('offered_course', models.ManyToManyField(to='application.course')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.coursename'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.grade'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.major'),
        ),
        migrations.CreateModel(
            name='ClassVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('available_time', models.ManyToManyField(to='application.availabletime')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city')),
                ('director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.province')),
                ('venue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.venuetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='availabletime',
            name='day_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='application.weekday'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preffered_style', models.CharField(blank=True, choices=[('V', 'Virtual'), ('FTF', 'Face_To_Face')], max_length=50, null=True)),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('registered_date', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('applicant', models.ManyToManyField(to='application.student')),
                ('demanded_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.course')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('class_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.classvenue')),
                ('edu_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationalvolunteer')),
                ('holding_time', models.ManyToManyField(to='application.availabletime')),
            ],
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('edu_level', 'grade_name'), name='unique_edu_level_grade'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_name', 'grade', 'major'), name='unique_course_name_edu_level_grade'),
        ),
        migrations.AddConstraint(
            model_name='availabletime',
            constraint=models.UniqueConstraint(fields=('day_name', 'time_name'), name='unique_day_name_time_name'),
        ),
    ]
