# Generated by Django 4.2.9 on 2024-02-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='demandend_venue',
            new_name='venue',
        ),
    ]
