# Generated by Django 4.2.9 on 2024-01-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='time_name',
            field=models.CharField(max_length=20),
        ),
    ]
