# Generated by Django 4.2.9 on 2024-01-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=11)),
                ('gpa', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
            preserve_default=False,
        ),
    ]
