# Generated by Django 4.2.9 on 2024-02-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_student_remove_application_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantstudent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='educationalvolunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='skilledvolunteer',
            name='address',
        ),
    ]
