# Generated by Django 4.2.9 on 2024-04-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_demandend_venue_application_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedapplication',
            name='class_venue',
        ),
        migrations.RemoveField(
            model_name='acceptedapplication',
            name='holding_time',
        ),
    ]
