# Generated by Django 4.2.9 on 2024-04-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_acceptedapplication_class_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedapplication',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acceptedapplication',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
