# Generated by Django 4.2.9 on 2024-01-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(max_length=20, verbose_name='پایه تحصیلی'),
        ),
    ]
