# Generated by Django 4.2.9 on 2024-01-13 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_grade_grade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='edu_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel', verbose_name='Preffered Level'),
        ),
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.grade', verbose_name='Preffered Grade'),
        ),
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.major', verbose_name='Preffered Major'),
        ),
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='offered_course',
            field=models.ManyToManyField(blank=True, null=True, to='application.course'),
        ),
    ]
