# Generated by Django 4.2.9 on 2024-02-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='demandend_time',
            field=models.ManyToManyField(blank=True, null=True, to='application.availabletime'),
        ),
        migrations.AlterField(
            model_name='application',
            name='demandend_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.classvenue'),
        ),
    ]
