# Generated by Django 4.2.9 on 2024-04-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_acceptedapplication_edu_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedapplication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
