# Generated by Django 4.2.9 on 2024-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_application_demandend_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='demandend_time',
        ),
        migrations.AddField(
            model_name='application',
            name='demandend_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
