# Generated by Django 4.2.9 on 2024-02-11 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_application_demandend_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='rating',
        ),
        migrations.AddField(
            model_name='application',
            name='num_of_student',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
