# Generated by Django 4.2.9 on 2024-04-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_acceptedapplication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedapplication',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
