# Generated by Django 4.2.9 on 2024-04-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_acceptedapplication_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school_type',
        ),
    ]
