# Generated by Django 4.2.9 on 2024-01-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_educationalvolunteer_offered_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='edu_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel', verbose_name='Preferred Level'),
        ),
        migrations.RemoveField(
            model_name='educationalvolunteer',
            name='grade',
        ),
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.major', verbose_name='Preferred Major'),
        ),
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='offered_course',
            field=models.ManyToManyField(blank=True, null=True, to='application.course'),
        ),
        migrations.AddField(
            model_name='educationalvolunteer',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.grade', verbose_name='Preferred Grade'),
        ),
    ]
