# Generated by Django 4.2.9 on 2024-01-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_educationalvolunteer_edu_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='preffered_style',
            field=models.CharField(blank=True, choices=[('V', 'مجازی'), ('FTF', 'حضوری')], max_length=50, null=True),
        ),
    ]
