# Generated by Django 4.2.9 on 2024-02-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_application_demanded_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='demanded_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.course'),
        ),
    ]
