# Generated by Django 4.2.9 on 2024-01-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_preffered_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='preffered_style',
            new_name='preferred_style',
        ),
    ]
