# Generated by Django 4.2.9 on 2024-02-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_demanded_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='demanded_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.course'),
            preserve_default=False,
        ),
    ]
