# Generated by Django 4.2.9 on 2024-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_preffered_style_application_preferred_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='offered_course',
            field=models.ManyToManyField(to='application.course'),
        ),
    ]
