# Generated by Django 4.2.9 on 2024-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_application_demanded_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='preferred_style',
            field=models.CharField(choices=[('V', 'مجازی'), ('FTF', 'حضوری')], default='V', max_length=50),
        ),
    ]
