# Generated by Django 4.2.9 on 2024-04-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_instituteprofile_venue_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstituteType',
        ),
    ]
