# Generated by Django 4.2.9 on 2024-02-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_application_preferred_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='demandend_time',
        ),
        migrations.AddField(
            model_name='application',
            name='free_day_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.weekday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='free_time_1',
            field=models.ForeignKey(default= 3 , on_delete=django.db.models.deletion.CASCADE, to='application.availabletime'),
            preserve_default=False,
        ),
    ]
