# Generated by Django 4.2.9 on 2024-04-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_delete_institutetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
