# Generated by Django 4.2.9 on 2024-01-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_educationalvolunteer_offered_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='registered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
