# Generated by Django 4.2.9 on 2024-02-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_application_demandend_time_and_more'),
    ]


