# Generated by Django 4.2.9 on 2024-01-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_application_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='registered_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
