# Generated by Django 4.2.9 on 2024-05-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nationality',
        ),
    ]
