# Generated by Django 4.2.9 on 2024-02-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_availabletime_day_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availabletime',
            name='unique_day_name_time_name',
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='day_name',
        ),
    ]
