# Generated by Django 4.2.9 on 2024-05-07 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_publicplace_district_alter_publicplace_name_and_more'),
        ('application', '0014_remove_applicant_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.publicplace'),
            preserve_default=False,
        ),
    ]
