# Generated by Django 4.2.9 on 2024-02-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_publicplace'),
        ('application', '0014_remove_availabletime_unique_day_name_time_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedapplication',
            name='class_venue',
        ),
        migrations.RemoveField(
            model_name='applicantstudent',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classvenue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='classvenue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='classvenue',
            name='director',
        ),
        migrations.RemoveField(
            model_name='classvenue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='classvenue',
            name='province',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='province',
        ),
        migrations.AlterField(
            model_name='application',
            name='demandend_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.publicplace'),
        ),
        migrations.AlterField(
            model_name='application',
            name='free_day_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.weekday'),
        ),
        migrations.AlterField(
            model_name='application',
            name='free_time_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.availabletime'),
        ),
    ]
