# Generated by Django 4.2.9 on 2024-02-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_remove_availabletime_unique_day_name_time_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='free_day_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.weekday'),
        ),
        migrations.AlterField(
            model_name='application',
            name='free_time_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.availabletime'),
        ),
    ]
