# Generated by Django 4.2.9 on 2024-05-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_schoolprofile_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
    ]
