# Generated by Django 4.2.9 on 2024-02-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_remove_acceptedapplication_class_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='free_day_1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='free_time_1',
        ),
    ]
