# Generated by Django 4.2.9 on 2024-01-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
