# Generated by Django 4.2.9 on 2024-02-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_remove_application_free_day_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='free_day_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.weekday'),
        ),
    ]
