# Generated by Django 4.2.9 on 2024-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_schoolprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='educational_district',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
