# Generated by Django 4.2.9 on 2024-02-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_application_free_day_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='free_time_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.availabletime'),
        ),
    ]
