# Generated by Django 4.2.9 on 2024-02-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_publicplace'),
        ('application', '0018_application_free_time_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedapplication',
            name='class_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.publicplace'),
        ),
    ]
