# Generated by Django 4.2.9 on 2024-01-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='book_download_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
