# Generated by Django 4.2.9 on 2024-05-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_publicplace_city_alter_publicplace_province'),
        ('application', '0018_alter_schoolprofile_educational_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteprofile',
            name='institute',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.publicplace'),
            preserve_default=False,
        ),
    ]
