# Generated by Django 4.2.9 on 2024-02-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_acceptedapplication_class_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='SchoolType',
        ),
    ]
