# Generated by Django 4.2.9 on 2024-01-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_educationallevel_url_title_grade_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationallevel',
            name='url_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='url_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
