# Generated by Django 4.2.9 on 2024-02-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_delete_school_delete_schooltype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassVenue',
        ),
        migrations.DeleteModel(
            name='VenueType',
        ),
    ]
