# Generated by Django 4.2.9 on 2024-05-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_instituteprofile_available_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
