# Generated by Django 4.2.9 on 2024-02-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_delete_classvenue_delete_venuetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_district', models.IntegerField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('school_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel')),
                ('school_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.schooltype')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('available_time', models.ManyToManyField(to='application.availabletime')),
                ('venue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.institutetype')),
            ],
        ),
    ]
