# Generated by Django 4.2.9 on 2024-01-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_major_url_title_alter_educationallevel_url_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationallevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='major',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
