# Generated by Django 4.2.9 on 2024-02-25 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_publicplace'),
        ('application', '0022_institutetype_schooltype_schoolprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.profile')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('IR', 'ایرانی'), ('F', 'اتباع')], max_length=300)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_worker', models.BooleanField(default=False)),
                ('special_condition', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('slug', models.SlugField(default='')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.grade')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.major')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.publicplace')),
            ],
            bases=('account.profile',),
        ),
        migrations.DeleteModel(
            name='ApplicantStudent',
        ),
    ]
