# Generated by Django 4.2.9 on 2024-05-11 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_volunteer'),
        ('application', '0023_remove_skilledvolunteer_job_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkilledVolunteer',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.volunteer')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('slug', models.SlugField(default='')),
                ('offered_skill', models.ManyToManyField(to='application.skill')),
            ],
            bases=('account.volunteer',),
        ),
        migrations.CreateModel(
            name='EducationalVolunteer',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.volunteer')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('offered_course', models.ManyToManyField(to='application.course')),
                ('preferred_edu_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.educationallevel', verbose_name='Preferred Level')),
                ('preferred_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.grade', verbose_name='Preferred Grade')),
                ('preferred_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.major', verbose_name='Preferred Major')),
            ],
            bases=('account.volunteer',),
        ),
    ]
