# Generated by Django 4.2.9 on 2024-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_skilledvolunteer_educationalvolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalvolunteer',
            name='teach_entrance_exam',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
