# Generated by Django 4.2.9 on 2024-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_educationalvolunteer_teach_entrance_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='offered_course',
            field=models.ManyToManyField(to='application.coursename'),
        ),
    ]
