# Generated by Django 4.2.9 on 2024-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_alter_educationalvolunteer_offered_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalvolunteer',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
