# Generated by Django 4.2.9 on 2024-05-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_alter_educationalvolunteer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_editing',
            field=models.BooleanField(default=False),
        ),
    ]
